export const USER_DETAILS_LOADING = "USER_DETAILS_LOADING";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_ERROR = "USER_DETAILS_ERROR";
export const REMOVE_USER_DETAILS = "REMOVE_USER_DETAILS";
